//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto3Capas.InsertarCliente {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InsertarCliente.ServicioWebProyectoSoap")]
    public interface ServicioWebProyectoSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsCliente", ReplyAction="*")]
        Proyecto3Capas.InsertarCliente.InsClienteResponse InsCliente(Proyecto3Capas.InsertarCliente.InsClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<Proyecto3Capas.InsertarCliente.InsClienteResponse> InsClienteAsync(Proyecto3Capas.InsertarCliente.InsClienteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsCliente", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto3Capas.InsertarCliente.InsClienteRequestBody Body;
        
        public InsClienteRequest() {
        }
        
        public InsClienteRequest(Proyecto3Capas.InsertarCliente.InsClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string apPaterno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string apMaterno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string rfc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string telefono;
        
        public InsClienteRequestBody() {
        }
        
        public InsClienteRequestBody(string nombre, string apPaterno, string apMaterno, string rfc, string telefono) {
            this.nombre = nombre;
            this.apPaterno = apPaterno;
            this.apMaterno = apMaterno;
            this.rfc = rfc;
            this.telefono = telefono;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsClienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto3Capas.InsertarCliente.InsClienteResponseBody Body;
        
        public InsClienteResponse() {
        }
        
        public InsClienteResponse(Proyecto3Capas.InsertarCliente.InsClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsClienteResult;
        
        public InsClienteResponseBody() {
        }
        
        public InsClienteResponseBody(string InsClienteResult) {
            this.InsClienteResult = InsClienteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioWebProyectoSoapChannel : Proyecto3Capas.InsertarCliente.ServicioWebProyectoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioWebProyectoSoapClient : System.ServiceModel.ClientBase<Proyecto3Capas.InsertarCliente.ServicioWebProyectoSoap>, Proyecto3Capas.InsertarCliente.ServicioWebProyectoSoap {
        
        public ServicioWebProyectoSoapClient() {
        }
        
        public ServicioWebProyectoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioWebProyectoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWebProyectoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWebProyectoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto3Capas.InsertarCliente.InsClienteResponse Proyecto3Capas.InsertarCliente.ServicioWebProyectoSoap.InsCliente(Proyecto3Capas.InsertarCliente.InsClienteRequest request) {
            return base.Channel.InsCliente(request);
        }
        
        public string InsCliente(string nombre, string apPaterno, string apMaterno, string rfc, string telefono) {
            Proyecto3Capas.InsertarCliente.InsClienteRequest inValue = new Proyecto3Capas.InsertarCliente.InsClienteRequest();
            inValue.Body = new Proyecto3Capas.InsertarCliente.InsClienteRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.apPaterno = apPaterno;
            inValue.Body.apMaterno = apMaterno;
            inValue.Body.rfc = rfc;
            inValue.Body.telefono = telefono;
            Proyecto3Capas.InsertarCliente.InsClienteResponse retVal = ((Proyecto3Capas.InsertarCliente.ServicioWebProyectoSoap)(this)).InsCliente(inValue);
            return retVal.Body.InsClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Proyecto3Capas.InsertarCliente.InsClienteResponse> Proyecto3Capas.InsertarCliente.ServicioWebProyectoSoap.InsClienteAsync(Proyecto3Capas.InsertarCliente.InsClienteRequest request) {
            return base.Channel.InsClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Proyecto3Capas.InsertarCliente.InsClienteResponse> InsClienteAsync(string nombre, string apPaterno, string apMaterno, string rfc, string telefono) {
            Proyecto3Capas.InsertarCliente.InsClienteRequest inValue = new Proyecto3Capas.InsertarCliente.InsClienteRequest();
            inValue.Body = new Proyecto3Capas.InsertarCliente.InsClienteRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.apPaterno = apPaterno;
            inValue.Body.apMaterno = apMaterno;
            inValue.Body.rfc = rfc;
            inValue.Body.telefono = telefono;
            return ((Proyecto3Capas.InsertarCliente.ServicioWebProyectoSoap)(this)).InsClienteAsync(inValue);
        }
    }
}
